# Generated by Django 5.0.1 on 2024-01-26 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RenameField(
            model_name='devicelog',
            old_name='check_in',
            new_name='givenDate',
        ),
        migrations.RenameField(
            model_name='devicelog',
            old_name='check_out',
            new_name='returnedDate',
        ),
        migrations.RemoveField(
            model_name='devicelog',
            name='check_in_condition',
        ),
        migrations.RemoveField(
            model_name='devicelog',
            name='check_out_condition',
        ),
        migrations.AddField(
            model_name='devicelog',
            name='given_condition',
            field=models.CharField(default='Good', max_length=100),
        ),
        migrations.AddField(
            model_name='devicelog',
            name='returned_condition',
            field=models.CharField(default='Good', max_length=100),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
